axis_linear: 1    #left axis up/down
scale_linear: 0.4
scale_linear_turbo: 0.6

axis_angular: 0    #left axis left/right
scale_angular: 0.8
scale_angular_turbo: 1.2

enable_button: 4        #L1 button
enable_turbo_button: 6  #L2 button
